import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SharingStatesContext from "../../useContexts/sharedStates";
import UserAxiosContext from "../../useContexts/UserAxios";
import Header from "./components/header/header";
import Footer from "./components/footer/footer";
import LoginRegister from "./components/popups/authorizationPopup/AuthorizationPopup";
import AlertCust from "./components/alertcust/AlertCust";
import CarsContext from "../../useContexts/CarsAxios";
import PartsContext from "../../useContexts/PartsAxios";
import ServcenterContext from "../../useContexts/ServCenterAxios";
import ServiceImgPopUp from "./components/popups/ServiceImgPopUp";
import MenuPopUp from "./components/popups/menuPopUp";
import UserMenuPopUp from "./components/popups/userMenuPopUp";
import CurrencyContext from "../../useContexts/CurrencyAxios";
import Carsfilterpopup from "./components/popups/filterpopups/carsfilterpopup";
import { BrowserRouter } from "react-router-dom";
import Partsfilterpopup from "./components/popups/filterpopups/partsfilterpopup";
import CarsVinImgPopUp from "./components/popups/carsVinImgPopUp";
import ProductserviceContext from "../../useContexts/ProductServicesAxios";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CARFAX - ახალი და მეორადი ავტომობილები",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SharingStatesContext>
          <UserAxiosContext>
            <CarsContext>
              <PartsContext>
                <ServcenterContext>
                  <CurrencyContext>
                    <ProductserviceContext>
                      <div className="bg-[#040A1C] w-full min-h-[100vh]">
                        <Header />
                        {children}
                        <Footer />
                        <LoginRegister />
                        <AlertCust />
                        <MenuPopUp />
                        <ServiceImgPopUp />
                        <UserMenuPopUp />
                        <Carsfilterpopup />
                        <Partsfilterpopup />
                        <CarsVinImgPopUp />
                      </div>
                    </ProductserviceContext>
                  </CurrencyContext>
                </ServcenterContext>
              </PartsContext>
            </CarsContext>
          </UserAxiosContext>
        </SharingStatesContext>
      </body>
    </html>
  );
}
